Repository MLSA-UET-Lahore-NC/BookWise-Frontend, pull requests merged in 2024-10, with the labels that each got.

#1 added features of search and discover
  package-lock.json
  package.json
  postcss.config.js
  src/app/components/SearchBar.js
  src/app/layout.js
  src/app/page.js
  tailwind.config.js
Labels: good first issue, hacktoberfest-accepted

#2 Comments and Discussion Thread
  components/Navbar/Navbar.jsx
  package-lock.json
  package.json
  src/app/Book/[id]/page.jsx
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  tailwind.config.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 ✨ New Feature: Dynamic Category Selection with Book Category from Dropdown
  src/app/Book/[id]/page.jsx
  src/app/page.js
Labels: enhancement, hacktoberfest-accepted

#4 wish list work done
  components/Navbar/Navbar.jsx
  src/app/components/WishlistManagement/page.jsx
  src/app/page.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#7 Added anchor tag to logo for navigating back to homepage
  components/Navbar/Navbar.jsx
Labels: hacktoberfest-accepted

#8 added reviews and ratings , added Home page
  public/assets/herosection.png
  src/app/components/Book.jsx
  src/app/components/BookReview.jsx
  src/app/components/BookThumbnail.jsx
  src/app/components/BooksData.jsx
  src/app/components/Herosection.jsx
  src/app/components/Navbar.jsx
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/pages/review/[Id].jsx
  tailwind.config.js
Labels: enhancement, good first issue, hacktoberfest-accepted
